name: Deploy GitHub Pages
run-name: ${{ github.ref_name }} is deploying GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build pages
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-artifact@v4

        with:
          name: pages
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

        with:
          repository: xiyaozhuang/action-target
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v4

        with:
          name: pages

      - name: Deploy pages
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Deployed pages"
          git push
